security:
  password_hashers:
    App\Entity\User:
      algorithm: auto

  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: username

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    # Frontend Firewall (Form Login)
    main:
      pattern: ^/(?!api) # Applies to all non-API routes
      lazy: true
      provider: app_user_provider
      form_login:
        login_path: login
        check_path: login
        default_target_path: expense_list
      logout:
        path: /logout

    # API Firewall (JWT Authentication)
    api:
      pattern: ^/api # Applies only to routes under /api
      stateless: true
      provider: app_user_provider
      jwt: ~

  access_control:
    - { path: ^/api, roles: IS_AUTHENTICATED_FULLY } # Protect all API routes
    #- { path: ^/admin, roles: ROLE_ADMIN } # Protect specific routes
