security:
  # Hashing passwords for the User class
  password_hashers:
    App\Entity\User:
      algorithm: auto

  # User provider configuration
  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: username

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      lazy: true
      provider: app_user_provider
      form_login:
        login_path: login
        check_path: login
        default_target_path: expense_list
      logout:
        path: /logout

  # Control access to routes based on roles
  access_control:
    # - { path: ^/admin, roles: ROLE_ADMIN }
    # - { path: ^/profile, roles: ROLE_USER }
